"""Embed art images as base64 data URLs for text-only GitHub deploy."""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "js" / "embedded-assets.js"


def data_url(path: Path) -> str:
    raw = path.read_bytes()
    b64 = base64.b64encode(raw).decode("ascii")
    # files are .png extension but may be jpeg content
    mime = "image/jpeg" if raw[:3] == b"\xff\xd8\xff" else "image/png"
    if path.suffix.lower() in {".jpg", ".jpeg"}:
        mime = "image/jpeg"
    return f"data:{mime};base64,{b64}"


def main():
    logo = ROOT / "assets" / "art" / "logo.png"
    bg = ROOT / "assets" / "art" / "bg-menu.png"
    pulse = ROOT / "assets" / "songs" / "pulse-drive" / "jacket.png"
    neon = ROOT / "assets" / "songs" / "neon-grid" / "jacket.png"

    for p in (logo, bg, pulse, neon):
        if not p.exists():
            raise SystemExit(f"missing {p}")

    content = f'''// Auto-generated by tools/embed_assets.py — do not edit by hand
export const EMBEDDED = {{
  logo: {data_url(logo)!r},
  bgMenu: {data_url(bg)!r},
  jackets: {{
    "pulse-drive": {data_url(pulse)!r},
    "neon-grid": {data_url(neon)!r},
  }},
}};
'''
    OUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
